#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa XXX aws-key
      - ssh-rsa XXX aws-key
ssh_pwauth: true
disable_root: false
package_update: true

packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - cron
  - awscli
  - jq

runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-mongosh
  - sudo systemctl enable apache2
  - sudo systemctl start apache2
  - export PATH=/usr/local/bin/aws:$PATH
  - sudo chmod +x /var/log/credentials.sh
  - sudo /var/log/credentials.sh

write_files:
  - path: /var/log/credentials.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Fetch secrets from AWS Secrets Manager and export them as environment variables
      export MONGODB_USERNAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_USERNAME --query SecretString --output text | jq -r .MONGODB_USERNAME | tr -d '[:space:]')
      export MONGODB_CLUSTER=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_CLUSTER --query SecretString --output text | jq -r .MONGODB_CLUSTER | tr -d '[:space:]')
      export MONGODB_DATABASE_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_DATABASE_NAME --query SecretString --output text | jq -r .MONGODB_DATABASE_NAME | tr -d '[:space:]')
      export MONGODB_COLLECTION_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_COLLECTION_NAME --query SecretString --output text | jq -r .MONGODB_COLLECTION_NAME | tr -d '[:space:]')
      export MONGODB_PASSWORD=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_PASSWORD --query SecretString --output text | jq -r .MONGODB_PASSWORD | tr -d '[:space:]')
      export S3_BUCKET_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id S3_BUCKET_NAME --query SecretString --output text | jq -r .S3_BUCKET_NAME | tr -d '[:space:]')
      export MONGODB_URI="mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER.tfgnmjn.mongodb.net/$MONGODB_DATABASE_NAME?retryWrites=true&w=majority&appName=$MONGODB_COLLECTION_NAME"

      # Persist the environment variables in /etc/profile for future sessions
      echo "export MONGODB_USERNAME=$MONGODB_USERNAME" >> /etc/profile
      echo "export MONGODB_CLUSTER=$MONGODB_CLUSTER" >> /etc/profile
      echo "export MONGODB_DATABASE_NAME=$MONGODB_DATABASE_NAME" >> /etc/profile
      echo "export MONGODB_COLLECTION_NAME=$MONGODB_COLLECTION_NAME" >> /etc/profile
      echo "export MONGODB_PASSWORD=$MONGODB_PASSWORD" >> /etc/profile
      echo "export S3_BUCKET_NAME=$S3_BUCKET_NAME" >> /etc/profile
      echo "export MONGODB_URI=$MONGODB_URI" >> /etc/profile

      cat <<EOF | sudo tee /etc/cron.d/update_metadata
      * * * * * root mongosh "mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_CLUSTER.tfgnmjn.mongodb.net/$MONGODB_DATABASE_NAME?retryWrites=true&w=majority&appName=$MONGODB_COLLECTION_NAME" --apiVersion 1 --username "$MONGODB_USERNAME" --password "$MONGODB_PASSWORD" --eval 'const metadata = db["$MONGODB_COLLECTION_NAME"].find().toArray(); print(JSON.stringify(metadata));' > /var/www/html/metadata.json
      EOF

  - path: /var/www/html/index.php
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Metadata Display</title>
          <meta http-equiv="refresh" content="60"> <!-- Refresh the page every 60 seconds -->
      </head>
      <body>
          <?php
          $metadata = null;
          $json_data = file_get_contents('/var/www/html/metadata.json');
          $metadata = json_decode($json_data, true);
          $bucket_url = 'https://praktischepruefungbucket.s3.amazonaws.com/';
          if (!empty($metadata)) {
              foreach ($metadata as $item) {
                  echo "<img src='{$bucket_url}{$item['id']}.jpg' width='400' /><br/>";
                  echo '<p>Photo ID: ' . $item['id'] . '</p>';
                  echo '<p>Description: ' . $item['description'] . '</p>';
                  echo '<p>Author: ' . $item['author'] . '</p>';
                  echo '<p>Labels: ' . '</p>';
                  foreach ($item['labels'] as $label) {
                      echo "<li>{$label['Name']} (Confidence: {$label['Confidence']}), </li>";
                  }
                  echo '</p>';
                  echo '<hr>';
              }
          } else {
              echo '<p>No metadata found or metadata format is invalid.</p>';
          }
          ?>
      </body>
      </html>

  - path: /var/www/html/metadata.json
    content: |-
      []