#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCK45plqXW1CWEgOx8d9nGWA9MrsC+E4YRAKMt1k4LCFvbm7fXqxvCVwhFjGSaSZwrIKZ+DMFF6oLipR6jx52CRn6qcjkncLM8oorrJUKs/BM4FXToqzDRKF9kI106qTUUCZThDk/Ktr1Tqd40PVkPmGP1xs1WjkmIOdQRAPgTSDJsY8Dfv8ndiF3IGezPaXKtKrFHVW2gXFbGPkuywaCrKjV6udVx9JGCf4mOQcHCEL3M7E2aAivPdC2LwV8fhTEjzPwUQUf4ClHNhqIGvdWEgEbI9ct4RIUkKWn9Y15hwOwJz5J/VTHdj836n+n/5Tgi9UK1s0DVIycYC1qew4RcR aws-key
ssh_pwauth: true
disable_root: false
package_update: true

packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - cron
  - awscli
  - jq

runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-mongosh
  - sudo systemctl enable apache2
  - sudo systemctl start apache2
  - export PATH=/usr/local/bin/aws:$PATH
  - sudo chmod +x /var/log/credentials.sh
  - sudo /var/log/credentials.sh

write_files:
  - path: /var/log/credentials.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      MONGODB_USERNAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_USERNAME --query SecretString --output text | jq -r .MONGODB_USERNAME | tr -d '[:space:]')
      MONGODB_CLUSTER=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_CLUSTER --query SecretString --output text | jq -r .MONGODB_CLUSTER | tr -d '[:space:]')
      MONGODB_DATABASE_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_DATABASE_NAME --query SecretString --output text | jq -r .MONGODB_DATABASE_NAME | tr -d '[:space:]')
      MONGODB_COLLECTION_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_COLLECTION_NAME --query SecretString --output text | jq -r .MONGODB_COLLECTION_NAME | tr -d '[:space:]')
      MONGODB_USERNAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_USERNAME --query SecretString --output text | jq -r .MONGODB_USERNAME | tr -d '[:space:]')
      MONGODB_PASSWORD=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_PASSWORD --query SecretString --output text | jq -r .MONGODB_PASSWORD | tr -d '[:space:]')
      MONGODB_CLUSTER=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id MONGODB_CLUSTER --query SecretString --output text | jq -r .MONGODB_CLUSTER | tr -d '[:space:]')
      S3_BUCKET_NAME=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id S3_BUCKET_NAME --query SecretString --output text | jq -r .S3_BUCKET_NAME | tr -d '[:space:]')

      echo $MONGODB_USERNAME
      echo $MONGODB_CLUSTER
      echo $MONGODB_DATABASE_NAME
      echo $MONGODB_COLLECTION_NAME
      echo $MONGODB_USERNAME
      echo $MONGODB_PASSWORD
      echo $MONGODB_CLUSTER
      echo $S3_BUCKET_NAME

      echo $MONGODB_USERNAME > /var/log/cred.txt
      echo $MONGODB_CLUSTER >> /var/log/cred.txt
      echo $MONGODB_DATABASE_NAME >> /var/log/cred.txt
      echo $MONGODB_COLLECTION_NAME >> /var/log/cred.txt
      echo $MONGODB_USERNAME >> /var/log/cred.txt
      echo $MONGODB_PASSWORD >> /var/log/cred.txt
      echo $MONGODB_CLUSTER >> /var/log/cred.txt
      echo $S3_BUCKET_NAME >> /var/log/cred.txt


  - path: /var/www/html/info.php
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Metadata Display</title>
          <meta http-equiv="refresh" content="60"> <!-- Refresh the page every 60 seconds -->
      </head>
      <body>
          <?php
          $metadata = null;
          $json_data = file_get_contents('/var/www/html/metadata.json');
          $metadata = json_decode($json_data, true);
          $bucket_url = 'https://{$S3_BUCKET_NAME}.s3.amazonaws.com/';

          if (!empty($metadata)) {
              foreach ($metadata as $item) {
                  echo "<p>{$bucket_url}{$item['id']}.jpg</p>";
                  echo "<img src='{$bucket_url}{$item['id']}.jpg' width='400' /><br/>";
                  echo '<p>Photo ID: ' . $item['id'] . '</p>';
                  echo '<p>Description: ' . $item['description'] . '</p>';
                  echo '<p>Author: ' . $item['author'] . '</p>';
                  echo '<p>Labels: ' . '</p>';
                  foreach ($item['labels'] as $label) {
                      echo "<li>{$label['Name']} (Confidence: {$label['Confidence']}), </li>";
                  }
                  echo '</p>';
                  echo '<hr>';
              }
          } else {
              echo '<p>$bucket_url</p>';

              echo '<p>No metadata found or metadata format is invalid.</p>';
          }
          ?>
      </body>
      </html>
  - path: /var/www/html/metadata.json
    content: |-
      []
